name: flutter_twilio_conversations
description: Integrate the Twilio Conversations SDK with your Flutter app using this Twilio Conversations Flutter plugin
version: 2.0.6+16
repository: https://github.com/Diversido/flutter_twilio_conversations
issue_tracker: https://github.com/Diversido/flutter_twilio_conversations/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_twilio_conversations_platform_interface:
    git:
      url: https://github.com/NicParmee-Kena/flutter_twilio_conversations_web.git
      path: flutter_twilio_conversations_platform_interface
      reg: e421e8ba9151f4677eb77524ad84d66eaf1f71d9
  flutter_twilio_conversations_web:
    git:
      url: https://github.com/NicParmee-Kena/flutter_twilio_conversations_web.git
      path: flutter_twilio_conversations_web
      reg: e421e8ba9151f4677eb77524ad84d66eaf1f71d9
  enum_to_string: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    implements: flutter_twilio_conversations
    platforms:
      android:
        package: twilio.flutter.twilio_conversations
        pluginClass: TwilioConversationsPlugin
      ios:
        pluginClass: TwilioConversationsPlugin
      web:
        default_package: flutter_twilio_conversations_web
